prebuilt_jar(
    name = 'hamcrest',
    binary_jar = 'hamcrest-core-1.3.jar',
    visibility = ['//:BuyAndroidPluginTests'],
)

prebuilt_jar(
    name = 'junit',
    binary_jar = 'junit-4.12.jar',
    visibility = ['//:BuyAndroidPluginTests'],
)
