android_aar(
    name = 'BuyAndroidPlugin',
    manifest_skeleton = 'AndroidManifest.xml',
    deps = [
        '//java/main/com/shopify/unity/buy:lib',
    ],
)

java_test(
    name = 'BuyAndroidPluginTests',
    srcs = glob(['java/test/**/*.java']),
    deps = [
        '//libs:junit',
        '//libs:hamcrest',
        '//java/main/com/shopify/unity/buy:lib',
    ]
)
