#!/usr/bin/env ruby

require 'net/http'
require 'json'
require 'optparse'
require 'graphql_schema'

require_relative './graphql_generator/csharp'

domain = "app.shopify.com"
shared_storefront_api_key = '4a6c829ec3cb12ef9004bf8ed27adf12' # this is the public key
storefront_api_version = '2020-01'
schema_filename = nil
ROOT_DIR = File.expand_path("../../..", __FILE__)
GENERATOR_DIR = File.expand_path("..", __FILE__)
TMP_DIR = File.join("#{GENERATOR_DIR}", "tmp/")
CACHED_SCHEMA_FILENAME = File.join("#{TMP_DIR}", "graphql_schema.json")

OptionParser.new do |opts|
  opts.banner = "Usage: ./script/update_schema [options]"

  opts.on("-d", "--dev", "Get development schema from app.myshopify.io") do
    domain = "app.myshopify.io"
  end
  opts.on("-fFILENAME", "--file=FILENAME", "Get schema from file") do |filename|
    schema_filename = filename
    domain = nil
  end
  opts.on("-c", "--cached-schema", "Used cached schema from last run") do |filename|
    schema_filename = CACHED_SCHEMA_FILENAME
    domain = nil
  end
end.parse!

if domain
  puts "Making tmp directory at #{TMP_DIR}"
  begin
    Dir.mkdir TMP_DIR
  rescue
    puts "tmp directory existed"
  end

  schema_filename = CACHED_SCHEMA_FILENAME

  schema_endpoint = "https://#{domain}/services/graphql/introspection/storefront?api_client_api_key=#{shared_storefront_api_key}&api_version=#{storefront_api_version}"

  begin
    body = Net::HTTP.get(URI(schema_endpoint))
    File.write(schema_filename, JSON.pretty_generate(JSON.parse(body)))
  rescue
    puts "Could not load schema from: #{schema_endpoint}, using cached file..."
    puts "Using cached file"
    schema_filename = CACHED_SCHEMA_FILENAME
    domain = nil
  end
end

schema = GraphQLSchema.new(JSON.parse(File.read(schema_filename)))
script_name = "scripts/generator/update_schema"

publish_destination = ARGV[0]

GraphQLGenerator::CSharp.new(
  schema,
  publish_destination,
  script_name: script_name,
  custom_scalars: [
    GraphQLGenerator::CSharp::Scalar.new(
      graph_type: 'DateTime',
      csharp_type: 'DateTime?',
      custom_cast: ->(value) { "Convert.ToDateTime(#{value})" },
    ),
    GraphQLGenerator::CSharp::Scalar.new(
      graph_type: 'Money',
      csharp_type: 'decimal',
      custom_cast: ->(value) { "Convert.ToDecimal(#{value})" },
    ),
  ]
).save("#{ROOT_DIR}/Assets/Shopify/Unity/Generated/");
